feat: point redemption
afif-hh/hh-new-ui-nuxt pull request #45
Opened 2023-02-07 08:27 UTC by fandihungryhub

Basecamp link : [https://3.basecamp.com/5190892/buckets/31126446/todos/5795267643](https://3.basecamp.com/5190892/buckets/31126446/todos/5795267643)

2023-02-08 05:25 UTC, afif-hh requested changes

2023-02-08 05:25 UTC, afif-hh commented on app.vue
> +import "@vueform/slider/themes/default.css";
ini jangan di taruh app.vue mas, karena jadi global alias tidak semua page perlu style ini

2023-02-08 05:25 UTC, afif-hh commented on components/HhBottomSheet.vue
> +<template>
udah ada bottom sheet nya mas, coba di pakai yg existing

2023-02-08 05:25 UTC, afif-hh commented on components/booking/PointRedemption.vue
> +<template>
kalau komponen kompleks gini di pindah ke `section` aja, folder `components` buat komponen yg bisa di reuse

2023-02-08 05:25 UTC, afif-hh commented on section/booking/BookingOffers.vue
> +import { $vfm as $modal } from "vue-final-modal";
harusnya import dari `lib/modal` mas jgn langsung dari `vue-final-modal`

2023-02-08 05:25 UTC, afif-hh commented on tailwind.config.js
> +      borderRadius: {
ini apa di pakai di banyak tempat ?

2023-02-08 05:25 UTC, afif-hh commented on components/booking/PointRedemption.vue
> +import Slider from "@vueform/slider";
coba dibikin dynamic import mas, biar ga masuk ke vendor.js setelah build seperti di `lib/swiper`

2023-02-08 05:25 UTC, afif-hh commented on components/icons/IconCircleMin.vue
> +<template>
pakai ini aja mas https://icones.js.org/collection/ic?s=add+circle+outline

2023-02-08 05:25 UTC, afif-hh commented on components/icons/IconCircleMin.vue
> +<template>
nggak perlu bikin komponen terpisah

2023-02-08 05:25 UTC, afif-hh commented on components/icons/IconCirclePlus.vue
> +<template>
ini juga

2023-02-08 14:10 UTC, fandihungryhub commented on app.vue
> +import "@vueform/slider/themes/default.css";
updated

2023-02-08 14:10 UTC, fandihungryhub commented on components/booking/PointRedemption.vue
> +<template>
updated

2023-02-08 14:11 UTC, fandihungryhub commented on tailwind.config.js
> +      borderRadius: {
updated, di hapus aja

2023-02-08 14:11 UTC, fandihungryhub commented on components/booking/PointRedemption.vue
> +import Slider from "@vueform/slider";
updated

2023-02-08 14:11 UTC, fandihungryhub commented on components/icons/IconCirclePlus.vue
> +<template>
updated

2023-02-13 06:11 UTC, afif-hh requested changes

2023-02-13 06:11 UTC, afif-hh commented on components/icons/IconCircleMin.vue
> +<template>
masih ada ini mas file nya ?

2023-02-13 06:11 UTC, afif-hh commented on components/icons/IconCirclePlus.vue
> +<template>
masih ada mas file nya

2023-02-13 06:11 UTC, afif-hh commented on components/booking/PointRedemption.vue
> +<template>
masih sama mas..

2023-02-13 07:44 UTC, fandihungryhub commented on components/icons/IconCircleMin.vue
> +<template>
ok udah di hapus

2023-02-13 07:44 UTC, fandihungryhub commented on components/icons/IconCirclePlus.vue
> +<template>
ok udah di hapus

2023-02-13 07:47 UTC, fandihungryhub commented on components/booking/PointRedemption.vue
> +<template>
ok udah di pindah

2023-02-13 07:47 UTC, fandihungryhub commented on components/HhBottomSheet.vue
> +<template>
ok udah pake yg existing

2023-02-13 09:06 UTC, afif-hh approved these changes

2023-02-13 09:06 UTC, merged