feat : create ui occasion
afif-hh/hh-new-ui-nuxt pull request #46
Opened 2023-02-08 04:30 UTC by afandi-siregar

https://3.basecamp.com/5190892/buckets/31126446/todos/5795267630

2023-02-08 12:46 UTC, afif-hh requested changes

2023-02-08 12:46 UTC, afif-hh commented on section/booking/BookingUserInfo.vue
> +export type SpecialRequest = {
ini buat apa ?

2023-02-08 12:46 UTC, afif-hh commented on partial/booking/BookingFlow.vue
> +  SpecialRequest,
BookingUserInfo jgn export SpecialRequest karena bukan tentang special request aja, bikin baru aja di `types/booking`

2023-02-08 12:46 UTC, afif-hh commented on components/HhInput.vue
> +<style lang="scss" scoped>
kyk nya bagus bikin `HHRadio` aja mas, yg HHInput biar fokus buat input type text dan sejenisnua

2023-02-09 04:09 UTC, afandi-siregar commented on section/booking/BookingUserInfo.vue
> +export type SpecialRequest = {
yang SpecialRequest untuk nampun object specialRequest mas, karena kan di UInya ada tanda garis pemisah, jangan aku mikir buat object, nntar tinggal di panggil 2 attribute di object itu

2023-02-14 03:56 UTC, afandi-siregar commented
done ya mas @afif-hh

2023-02-14 07:38 UTC, afif-hh approved these changes

2023-02-14 07:38 UTC, merged