feat: gift card list
afif-hh/hh-new-ui-nuxt pull request #47
Opened 2023-02-09 18:23 UTC by afandi-siregar

https://3.basecamp.com/5190892/buckets/31126446/todos/5795267653

2023-02-13 06:08 UTC, afif-hh requested changes

2023-02-13 06:08 UTC, afif-hh commented on section/booking/GiftCard/GiftCard.vue
> +import LstGiftCard from "./ListGiftCard.vue";
typo

2023-02-13 06:08 UTC, afif-hh commented on section/booking/GiftCard/ListGiftCard.vue
> +  <div class="mt-4">
ini di pindah ke component aja, terus namanya `GiftCard.vue` aja

2023-02-13 06:08 UTC, afif-hh commented on section/booking/GiftCard/ListGiftCard.vue
> +  // giftCards.value.map((giftCard) => {
ini di hapus

2023-02-13 06:08 UTC, afif-hh commented on section/booking/GiftCard/GiftCard.vue
> +function selectGiftCard(value: any) {
harusnya bisa tanpa pakai `any` mas

2023-02-13 06:08 UTC, afif-hh commented on section/booking/GiftCard/GiftCard.vue
> +  name: "GiftCard",
diganti nama ke `SelectGiftCard.vue` dan di pindahin ke folder komponen

2023-02-14 05:31 UTC, afandi-siregar commented
done mas @afif-hh

2023-02-16 12:36 UTC, closed without merging