feat : payment ui
afif-hh/hh-new-ui-nuxt pull request #54
Opened 2023-02-17 04:29 UTC by afandi-siregar

https://3.basecamp.com/5190892/buckets/31126446/todos/5795267578

2023-02-20 06:09 UTC, afif-hh requested changes

2023-02-20 06:09 UTC, afif-hh commented on components/booking/Payment/CreditCard.vue
> +<template>
buat props yg compatible dengan v-model

2023-02-20 06:09 UTC, afif-hh commented on section/booking/BookingPayment.vue
> +import IcTrueWallet from "~icons/fontisto/google-wallet";
icon" ini di hapus yg ga kepakai

2023-02-20 06:09 UTC, afif-hh commented on section/booking/BookingPayment.vue
> +import IcTrueWallet from "~icons/fontisto/google-wallet";
pakais asset nya hh aja biar sesuai

2023-02-20 06:18 UTC, afandi-siregar commented on section/booking/BookingPayment.vue
> +import IcTrueWallet from "~icons/fontisto/google-wallet";
udh aku perbaiki ini mas, di commit terakhir

2023-02-20 06:18 UTC, afandi-siregar commented on components/booking/Payment/CreditCard.vue
> +<template>
oke mas

2023-02-21 07:40 UTC, afif-hh requested changes

2023-02-21 07:40 UTC, afif-hh commented on components/booking/BookingSection.vue
> +  tooltip: {
nggak perlu props tooltip deh, cuman slot aja gpp

2023-02-21 07:40 UTC, afif-hh commented on components/booking/BookingSectionTitle.vue
> +    tooltip: {
nggak perlu props tooltip deh, cuman slot aja gpp

2023-02-21 07:40 UTC, afif-hh commented on components/booking/Payment/CreditCard.vue
> +<template>
ini masih salah, coba aja di panggil di parent nya kyk gini 

![image](https://user-images.githubusercontent.com/100819694/220279298-9acfa361-a9df-43ff-9b18-053d5b19ad15.png)

2023-02-21 07:40 UTC, afif-hh commented on section/booking/BookingPayment.vue
> +        :cc-number="ccNumber"
coba pakai v-model kyk gini 
![image](https://user-images.githubusercontent.com/100819694/220279397-b0a35570-1780-4e42-a972-d439f124149d.png)

2023-02-21 09:36 UTC, afif-hh requested changes

2023-02-21 09:36 UTC, afif-hh commented on components/booking/Payment/CreditCard.vue
> +          v-model="ccName"
ga bisa kyk gini mas, coba aja di local

2023-02-21 09:55 UTC, afif-hh approved these changes

2023-02-21 09:55 UTC, merged