feat: add booking delivery (wip)
afif-hh/hh-new-ui-nuxt pull request #56
Opened 2023-02-22 08:11 UTC by fandihungryhub

https://3.basecamp.com/5190892/buckets/31126446/todos/5856069000

2023-02-28 07:30 UTC, afif-hh commented
@fandihungryhub conflict

2023-02-28 12:33 UTC, afif-hh requested changes

2023-02-28 12:33 UTC, afif-hh commented on api/book/orderTimeEstimation.ts
> +  packages: any[];
ini

2023-02-28 12:33 UTC, afif-hh commented on api/book/getDistance.ts
> +  min_distance: number;
ini

2023-02-28 12:33 UTC, afif-hh commented on package.json
> +    "vue-tippy": "v6",
kalau bisa pakai native nya

2023-02-28 12:33 UTC, afif-hh commented on pages/hybrid/booking.vue
> +      bookingStore.location = {
validasi value dari client pakai zod

2023-02-28 12:33 UTC, afif-hh commented on pages/hybrid/booking.vue
> +      bookingStore.bookingMethod = "delivery";
"delivery" udah ada enum di `bookingServiceTypeSchema`

2023-02-28 12:33 UTC, afif-hh commented on pages/hybrid/booking.vue
> +      const parsedData = !isWebClient ? convertToJsonObject(data) : data;
validasi event pakai zod

2023-02-28 12:33 UTC, afif-hh commented on section/booking/BookingDelivery.vue
> +const {
coba di refactor pakai props

2023-02-28 12:33 UTC, afif-hh commented on section/booking/BookingDelivery.vue
> +  if (bookingMethod.value === "pick_up") {
pick_up pakai yg udah ada

2023-03-01 06:14 UTC, fandihungryhub commented on api/book/getDistance.ts
> +  min_distance: number;
ini apa ya? gak ada any value nya

2023-03-01 06:14 UTC, fandihungryhub commented on pages/hybrid/booking.vue
> +      bookingStore.location = {
updated

2023-03-01 06:14 UTC, fandihungryhub commented on pages/hybrid/booking.vue
> +      bookingStore.bookingMethod = "delivery";
updated

2023-03-01 06:14 UTC, fandihungryhub commented on pages/hybrid/booking.vue
> +      const parsedData = !isWebClient ? convertToJsonObject(data) : data;
updated

2023-03-01 06:14 UTC, fandihungryhub commented on section/booking/BookingDelivery.vue
> +const {
updated

2023-03-01 06:15 UTC, fandihungryhub commented on section/booking/BookingDelivery.vue
> +  if (bookingMethod.value === "pick_up") {
updated

2023-03-01 07:51 UTC, fandihungryhub commented on package.json
> +    "vue-tippy": "v6",
barusan nyoba lagi error mas, mungkin bisa dicari tau di cooldown

2023-03-01 08:41 UTC, afif-hh approved these changes

2023-03-01 08:41 UTC, merged