feat: saved credit card
afif-hh/hh-new-ui-nuxt pull request #62
Opened 2023-02-27 12:11 UTC by fandihungryhub

2023-03-01 08:57 UTC, afif-hh commented on api/credit_card/createCreditCard.ts
> +  access_token: string;
harunys camelCase

2023-03-01 09:57 UTC, fandihungryhub commented on api/credit_card/createCreditCard.ts
> +  access_token: string;
updated

2023-03-02 09:31 UTC, afif-hh requested changes

2023-03-02 12:11 UTC, fandihungryhub commented on components/booking/Payment/CreditCardGuest.vue
> +import { useCreditCardStore } from "~~/stores/creditCard";
updated

2023-03-02 12:12 UTC, fandihungryhub commented on components/booking/Payment/CreditCardGuest.vue
> +  /*paymentMethod.value = "";
updated

2023-03-03 02:40 UTC, afif-hh approved these changes

2023-03-03 02:40 UTC, merged